default:
  http_metas:
    content-type: text/html

  metas:
    title:         Veranet
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [ ../zerocall/style/style.css]

  javascripts:    [../zerocall/js/jquery-1.4.2.min.js, ../zerocall/js/jquery.jcarousel.min.js, ../zerocall/js/carousel.js, jquery.formatCurrency-1.3.0.min.js, i18n/jquery.formatCurrency.all.js]

  has_layout:     on
  layout:         layout
